{"version":3,"file":"external-exception-filter.js","sourceRoot":"/Users/hanxiaoxue/Documents/work/frontEndDebugger/nest/packages/core/","sources":["exceptions/external-exception-filter.ts"],"names":[],"mappings":";;;AAAA,2CAAsE;AAEtE,MAAa,uBAAuB;IAGlC,KAAK,CAAC,SAAY,EAAE,IAAmB;QACrC,IAAI,SAAS,YAAY,KAAK,IAAI,CAAC,CAAC,SAAS,YAAY,sBAAa,CAAC,EAAE;YACvE,uBAAuB,CAAC,MAAM,CAAC,KAAK,CAAC,SAAS,CAAC,OAAO,EAAE,SAAS,CAAC,KAAK,CAAC,CAAC;SAC1E;QACD,MAAM,SAAS,CAAC;IAClB,CAAC;;AAPuB,8BAAM,GAAG,IAAI,eAAM,CAAC,mBAAmB,CAAC,CAAC;AADtD,0DAAuB","sourcesContent":["import { ArgumentsHost, HttpException, Logger } from '@nestjs/common';\n\nexport class ExternalExceptionFilter<T = any, R = any> {\n  private static readonly logger = new Logger('ExceptionsHandler');\n\n  catch(exception: T, host: ArgumentsHost): R | Promise<R> {\n    if (exception instanceof Error && !(exception instanceof HttpException)) {\n      ExternalExceptionFilter.logger.error(exception.message, exception.stack);\n    }\n    throw exception;\n  }\n}\n"]}